### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by M-AminAlizadeh** [M-AminAlizadeh/catalog-of-my-things#29]
The GitHub project [Link](https://github.com/users/M-AminAlizadeh/projects/3)

Our group consists of three persons:

1. Amin Alizadeh (team member 1) [Issues from 1 - 9]
2. Agneta Pupienyte (team member 2)  [Issues from 10 - 18]
3. Tanmayi Manku (team member 3) [Issues from 19 - 27]

**The issue 28 is a group task and it's assigned to everyone**

**Comment by thecodechaser** [comment]
## STATUS: APPROVED 🟢

## Hi @M-AminAlizadeh, @tan12082001, and @agneta1991👋, 

Your project is complete!  There is nothing else to say other than... it's time to close it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
